### ISSUE TITLE
set up production dns

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-spills#62]
We need to request a production DNS for this project: `deqspills.ugrc.utah.gov`

@nathankota Can you help with the DNS request?

**Comment by nathankota** [comment]
INC1493876

**Comment by stdavis** [comment]
Looks like the SSL cert isn't working yet.
![image](https://user-images.githubusercontent.com/1326248/122818518-8bf5c800-d296-11eb-9c4a-bfa9c41530c2.png)

I believe that @steveoh needs to add the custom domain to [firebase hosting](https://console.firebase.google.com/u/1/project/ut-dts-agrc-spills-prod/hosting/sites).

**Comment by steveoh** [comment]
Please request to the cloud machine to add the production dns to ut-dts-agrc-spills-prod's firebase hosting. Since there is no existing DNS to swap, we can do this whenever without side effects. We will need to provide deq with new urls to embed once this is complete and work on a mapserv web server deprecation porter issue.

**Comment by nathankota** [comment]
INC1495157

**Comment by stdavis** [comment]
🙌
